using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace PurplePen.ViewModels
{
    /// <summary>Describes a failed inspection-package import without including presentation text.</summary>
    public enum MobileControlInspectionImportError
    {
        None,
        InvalidPackage,
        CourseMismatch
    }

    /// <summary>View model for reviewing and exchanging field inspection data for the active course.</summary>
    public partial class MobileControlInspectionDialogViewModel : ViewModelBase
    {
        private readonly List<MobileControlInspectionEntry> overview = new List<MobileControlInspectionEntry>();
        private CourseDesignator? courseDesignator;

        /// <summary>Creates an empty view model for the Avalonia designer.</summary>
        public MobileControlInspectionDialogViewModel() { }

        /// <summary>Controls in course order. Status, observed code and comments are editable.</summary>
        public ObservableCollection<MobileControlInspectionRowViewModel> Controls { get; } = new ObservableCollection<MobileControlInspectionRowViewModel>();

        /// <summary>JSON prepared by the export command; a host can save it using its own file service.</summary>
        [ObservableProperty]
        private string exportedJson = String.Empty;

        /// <summary>JSON supplied by a host, clipboard bridge or mobile service for import.</summary>
        [ObservableProperty]
        private string importJsonText = String.Empty;

        /// <summary>Error type from the most recent JSON import, for localized presentation by the view.</summary>
        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(HasImportError))]
        private MobileControlInspectionImportError importError = MobileControlInspectionImportError.None;

        /// <summary>Conflicts reported by the most recent import.</summary>
        public ObservableCollection<MobileControlInspectionConflict> Conflicts { get; } = new ObservableCollection<MobileControlInspectionConflict>();

        /// <summary>Statuses exposed for the editable status selector.</summary>
        public IReadOnlyList<MobileControlInspectionStatus> StatusValues { get; } =
            Enum.GetValues<MobileControlInspectionStatus>();

        /// <summary>Gets whether the last import had unknown, missing or changed controls.</summary>
        public bool HasConflicts { get { return Conflicts.Count != 0; } }

        /// <summary>Gets whether the most recent import had an error that should be shown to the user.</summary>
        public bool HasImportError { get { return ImportError != MobileControlInspectionImportError.None; } }

        /// <summary>Loads the inspection overview generated by the core.</summary>
        public void Load(EventDB eventDB, CourseDesignator courseDesignator)
        {
            if (eventDB == null)
                throw new ArgumentNullException(nameof(eventDB));
            if (courseDesignator == null)
                throw new ArgumentNullException(nameof(courseDesignator));

            this.courseDesignator = courseDesignator;
            overview.Clear();
            overview.AddRange(MobileControlInspection.CreateOverview(eventDB, courseDesignator));
            LoadRows();
        }

        /// <summary>Loads a supplied overview, useful for mobile clients and unit tests.</summary>
        public void LoadOverview(IEnumerable<MobileControlInspectionEntry> entries, CourseDesignator designator)
        {
            if (entries == null)
                throw new ArgumentNullException(nameof(entries));
            if (designator == null)
                throw new ArgumentNullException(nameof(designator));
            courseDesignator = designator;
            overview.Clear();
            overview.AddRange(entries);
            LoadRows();
        }

        /// <summary>Creates an export package from the current editable rows.</summary>
        public MobileControlInspectionPackage CreatePackage()
        {
            if (courseDesignator == null)
                throw new InvalidOperationException("An inspection overview must be loaded first.");
            MobileControlInspectionPackage package = MobileControlInspectionPackageSerializer.CreateFromOverview(overview, courseDesignator);
            foreach (MobileControlInspectionRowViewModel row in Controls) {
                MobileControlInspectionRecord record = package.Controls.First(item => item.ControlId == row.ControlId.id);
                row.CopyTo(record);
            }
            return package;
        }

        /// <summary>Returns portable JSON without involving a file system.</summary>
        public string ExportPackageJson()
        {
            return MobileControlInspectionPackageSerializer.Serialize(CreatePackage());
        }

        /// <summary>Imports JSON, merges it with the current overview and exposes all conflicts.</summary>
        public MobileControlInspectionMergeResult ImportPackageJson(string json)
        {
            if (courseDesignator == null)
                throw new InvalidOperationException("An inspection overview must be loaded first.");

            try {
                MobileControlInspectionPackage package = MobileControlInspectionPackageSerializer.Deserialize(json);
                MobileControlInspectionPackageSerializer.ValidatePackageForCourse(package, courseDesignator);
                MobileControlInspectionMergeResult result = MobileControlInspectionPackageSerializer.Merge(package, overview);
                Controls.Clear();
                foreach (MobileControlInspectionEntry entry in overview) {
                    MobileControlInspectionRecord record = result.Controls.First(item => item.ControlId == entry.ControlId.id);
                    Controls.Add(new MobileControlInspectionRowViewModel(entry, record));
                }
                Conflicts.Clear();
                foreach (MobileControlInspectionConflict conflict in result.Conflicts)
                    Conflicts.Add(conflict);
                OnPropertyChanged(nameof(HasConflicts));
                ExportedJson = String.Empty;
                ImportError = MobileControlInspectionImportError.None;
                return result;
            }
            catch (MobileControlInspectionPackageCourseMismatchException) {
                ImportError = MobileControlInspectionImportError.CourseMismatch;
                throw;
            }
            catch (ArgumentException) {
                ImportError = MobileControlInspectionImportError.InvalidPackage;
                throw;
            }
        }

        /// <summary>Prepares the current package for a host-provided save operation.</summary>
        [RelayCommand]
        private void PrepareExport()
        {
            ExportedJson = ExportPackageJson();
        }

        /// <summary>Imports package JSON supplied by a host, clipboard or mobile service.</summary>
        [RelayCommand]
        private void ImportJson()
        {
            if (String.IsNullOrWhiteSpace(ImportJsonText))
                return;

            try {
                ImportPackageJson(ImportJsonText);
            }
            catch (ArgumentException) {
                // The localized error enum is already set by ImportPackageJson.
            }
        }

        private void LoadRows()
        {
            Controls.Clear();
            foreach (MobileControlInspectionEntry entry in overview)
                Controls.Add(new MobileControlInspectionRowViewModel(entry));
            Conflicts.Clear();
            OnPropertyChanged(nameof(HasConflicts));
            ExportedJson = String.Empty;
            ImportError = MobileControlInspectionImportError.None;
        }

        /// <summary>Refreshes enum labels after the UI culture changes.</summary>
        public void RefreshLocalizedPresentation()
        {
            foreach (MobileControlInspectionRowViewModel row in Controls)
                row.RefreshLocalizedPresentation();
        }
    }

    /// <summary>Editable presentation row for one control inspection entry.</summary>
    public partial class MobileControlInspectionRowViewModel : ObservableObject
    {
        public MobileControlInspectionRowViewModel(MobileControlInspectionEntry entry)
            : this(entry, null) { }

        public MobileControlInspectionRowViewModel(MobileControlInspectionEntry entry, MobileControlInspectionRecord? record)
        {
            if (entry == null)
                throw new ArgumentNullException(nameof(entry));
            Sequence = entry.SequenceNumber;
            ControlId = entry.ControlId;
            Code = entry.ControlCode ?? String.Empty;
            Kind = entry.Kind;
            Location = String.Format("{0:0.##}, {1:0.##}", entry.Location.X, entry.Location.Y);
            ExpectedCode = entry.ControlCode ?? String.Empty;
            HasCode = entry.Kind == ControlPointKind.Normal && !String.IsNullOrEmpty(entry.ControlCode);
            if (record != null) {
                Status = record.Status;
                Comment = record.Comment ?? String.Empty;
                ObservedCode = record.ObservedCode ?? String.Empty;
                Latitude = record.Latitude;
                Longitude = record.Longitude;
                AccuracyMeters = record.AccuracyMeters;
                ObservedAtUtc = record.ObservedAtUtc;
                PhotoReferencePaths = new List<string>(record.PhotoReferencePaths ?? new List<string>());
            }
        }

        public int Sequence { get; }
        public Id<ControlPoint> ControlId { get; }
        public string Code { get; }
        public string ExpectedCode { get; }
        public ControlPointKind Kind { get; }
        public string Location { get; }
        public bool HasCode { get; }

        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(CodeValidationStatus))]
        private MobileControlInspectionStatus status = MobileControlInspectionStatus.Uninspected;

        [ObservableProperty]
        private string comment = String.Empty;

        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(CodeValidationStatus))]
        private string observedCode = String.Empty;

        [ObservableProperty] private double? latitude;
        [ObservableProperty] private double? longitude;
        [ObservableProperty] private double? accuracyMeters;
        [ObservableProperty] private DateTimeOffset? observedAtUtc;

        public List<string> PhotoReferencePaths { get; private set; } = new List<string>();

        /// <summary>Gets the code validation result for the editable observed code.</summary>
        public MobileControlCodeValidationStatus CodeValidationStatus {
            get { return MobileControlInspectionPackageSerializer.ValidateObservedCode(ExpectedCode, ObservedCode); }
        }

        /// <summary>Re-raises presentation properties so view-side enum converters use the new UI culture.</summary>
        internal void RefreshLocalizedPresentation()
        {
            OnPropertyChanged(nameof(Status));
            OnPropertyChanged(nameof(CodeValidationStatus));
        }

        internal void CopyTo(MobileControlInspectionRecord record)
        {
            record.Status = Status;
            record.Comment = Comment ?? String.Empty;
            record.ObservedCode = ObservedCode ?? String.Empty;
            record.Latitude = Latitude;
            record.Longitude = Longitude;
            record.AccuracyMeters = AccuracyMeters;
            record.ObservedAtUtc = ObservedAtUtc;
            record.PhotoReferencePaths = new List<string>(PhotoReferencePaths);
        }
    }
}
